### ISSUE TITLE
consider adding [an option to] print a message at the start of each recompile.

### ISSUE THREAD

**Issue by elenzil** [jshrake/grimoire#43]
when saving changes to source,
it's sometimes nice to see positive confirmation that compilation succeeded.

**Comment by elenzil** [comment]
so afaict, Grimoire doesn't output anything to stdout currently: just stderr when there's trouble.
what's your thought about a feature like this which would be printing to stdout ?

in other news, i implemented a version of this but it feels not in keeping with the rest of the codebase, in terms of how it's printing etc.  i've never worked with Rust and honestly i'm finding it a bit convoluted from my C11 perspective. perhaps i should read the manual ;)

**Comment by jshrake** [comment]
Hi! I updated a few of the debug! statements to info! statements so that you can see successful shader compilations notices when running with `RUST_LOG=info`. 

> Grimoire doesn't output anything to stdout currently: just stderr when there's trouble.
what's your thought about a feature like this which would be printing to stdout ?

I use the [log crate](https://docs.rs/log/0.4.6/log/) to manage logging. You'll need to specify the environment variable `RUST_LOG=info` to see these log messages. I updated the README to mention this environment variable as well.

**Comment by jshrake** [comment]
Note that you could also run with `RUST_LOG=debug`, but it logs a lot of messages that aren't immediately useful. I'm not really pleased with the current logging situation in grimoire and plan to overhaul it at some point, as with all things :P

**Comment by elenzil** [comment]
sweet!

thanks for your patience with my fumbling through Rust.  eg `cargo run` instead of `target/debug/...`.
