### ISSUE TITLE
Consider migrating from SDL2 to winit

### ISSUE THREAD

**Issue by jshrake** [jshrake/grimoire#7]
[winit](https://github.com/tomaka/winit) is a window handling library in pure Rust. Ideally grimoire would only depend on pure rust crates. Note that ggez is making a similar migration https://github.com/ggez/ggez/issues/391

I would like to understand how this would impact the ability to get grimoire running on mobile (iOS, Android), web (emscripten), and various VR/AR platforms.

**Comment by francesca64** [comment]
> I would like to understand how this would impact the ability to get grimoire running on mobile (iOS, Android), web (emscripten), and various VR/AR platforms.

winit's iOS and Android support is pretty thin, i.e. touch events are broken on iOS and both emit few events in general. For just rendering, Android works fine, but iOS requires more work in glutin before it will get past a black screen. The major issue blocking Android progress is lack of [JNI support](tomaka/android-rs-glue/pull/116), whereas the major issue blocking iOS progress is the lack of people invested enough to fix things (and how slow iOS Simulator runs on my computer, which is part of a more general problem about it being unpleasant to work on).

Our Emscripten backend *looks* pretty good, which is all I can say, since I've yet to succeed in getting anything to run in the browser. I'm fairly certain that's from build/toolchain issues on my part, though. If you're also interested in WASM, other people are too, and winit will conceivably support that in the not-too-distant future (a few people have volunteered). If/when that happens, it's very likely that no one will be interested in working on the Emscripten backend anymore (...not that anyone is currently).

I have to put a big fat proviso on all of this by saying that these three backends are in a state of neglect. There's been no issue reports to any of them in at least the past 6 months, and nobody noticed that glutin's iOS backend *didn't even compile* for the past year, so it's safe to say that nobody actually uses these backends. There's nothing I can really do about that, since it's already pretty ridiculous that I'm responsible for the three major desktop platforms.

I don't know anything about VR/AR, but winit isn't set in stone, so unless it's something you need in the short-term a good solution can likely be worked out.
